---
- name: Set persistent DNS servers
  ansible.builtin.copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    backup: yes
  become: true

- name: Update running DNS servers
  systemd:
    name: systemd-resolved
    daemon_reload: yes
    state: restarted

